### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by ShadeB**
Can someone please update the babel dependency installation instructions, on the study guide specifically  in the processJs section of the gulp labs? Thanks. Command should be: npm install --save-dev gulp-babel @babel/core @babel/preset-env

### CODE REVIEW

**Comment by ShadeB** [comment]
@googlebot I signed it!

**Comment by DavidScales** [comment]
Thanks for the PR ShadeB. I wasn't able to get this solution code to build:

```
dscales (patch-1) solution $ pwd
.../pwa-training-labs/gulp-lab/solution
dscales (patch-1) solution $ npm install
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/core@^6.26.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'solution'
npm ERR! notarget 
```

I tried running through the install steps, replacing the original `npm install --save-dev gulp-babel babel-core babel-preset-env` with your suggested `npm install --save-dev gulp-babel @babel/core @babel/preset-env` to get the latest version of all packages:

 ```
 "devDependencies": {
    "@babel/core": "^7.7.0",
    "@babel/preset-env": "^7.7.1",
    "browser-sync": "^2.26.7",
    "gulp": "^4.0.0",
    "gulp-babel": "^8.0.0",
    "gulp-clean-css": "^4.2.0",
    "gulp-rename": "^1.4.0",
    "gulp-uglify": "^3.0.2"
  }
```

Which seems to have alleviated the install error. However, I cannot successfully run the `processJs` gulp task:

```
dscales (patch-1 *) project $ gulp processJs
[16:09:47] Using gulpfile ~/.../pwa-training-labs/gulp-lab/project/gulpfile.js
[16:09:47] Starting 'processJs'...
[16:09:47] 'processJs' errored after 56 ms
[16:09:47] Error in plugin "gulp-babel"
Message:
    Cannot find module 'babel-preset-env' from '/.../pwa-training-labs/gulp-lab/project'
- Did you mean "@babel/env"?
```

I have not used gulp in a pretty long time. Is there any chance a step is missing?

**Comment by ShadeB** [comment]
My package.json file looks similar to yours but it runs, the only difference is I haven't removed the unsupported dependencies which shouldn't be the problem. here is my package file:
`"devDependencies": {
    "@babel/core": "^7.7.0",
    "@babel/preset-env": "^7.7.1",
    "babel-core": "^6.26.3",
    "babel-preset-env": "^1.7.0",
    "browser-sync": "^2.26.7",
    "gulp": "^4.0.0",
    "gulp-babel": "^8.0.0"
  }`
which runs with the following result:
`[08:53:31] Using gulpfile ~\Desktop\JavaScript\pwa-training-labs\gulp-lab\project\gulpfile.js
[08:53:32] Starting 'processJs'...
[08:54:34] Finished 'processJs' after 1.03 min`
Let me try to use your package configuration and see what results I get.

**Comment by ShadeB** [comment]
Okay I reproduced the error on my system and after some research I found out how that can be rectified. edit the presets part of your processJs function in your gulpfile.js file from:

`presets: ['env']`

To this:

`presets: ['@babel/env']`

It should run successfully now.

**Comment by DavidScales** [comment]
Awesome! looks like you put that change in a new PR (#63) though, could you move it into this PR so we can merge the two changes (gulpfile.js & package.json) together?

**Comment by ShadeB** [comment]
Done.

**Comment by DavidScales** [comment]
LGTM! Thanks again @ShadeB. We can merge it in once we get the corresponding instructions updated

@sarahec I have made the corresponding suggestions on the source doc ("4.1 Lab: Gulp setup") but I'm not sure if other docs have been forked or what the republishing flow is these days (is it just published as a Codelab?). Do you know how I can go about republishing?

**Pull request merged**
